name: Build and Deploy

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 20

         - name: Install dependencies
           run: npm ci

         - name: Build project
           run: npx gulp build

         - name: Install dependencies (rsync and sshpass)
           run: sudo apt-get install -y rsync sshpass

         - name: Deploy to server
           run: |
              sshpass -p ${{ secrets.SERVER_PASSWORD }} rsync -avz --delete --progress -e 'ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}' dist/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/jcb/sites/test.aquaice.us
           shell: bash
