name: Build and Deploy

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 20

         - name: Install dependencies
           run: npm ci

         - name: Check server connectivity
           run: ping -c 3 ${{ secrets.SERVER_HOST }}

         - name: Build project
           run: npx gulp build

         - name: Install dependencies (rsync)
           run: sudo apt-get install -y rsync

         - name: Set up SSH
           run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
              chmod 600 private_key
              mkdir -p ~/.ssh
              ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

         - name: Deploy to server
           run: |
              rsync -avz --delete --progress -e "ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" dist/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/jcb/sites/test.aquaice.us
